test npm release

diff --git a/release-publish/action.yaml b/release-publish/action.yaml
--- a/release-publish/action.yaml
+++ b/release-publish/action.yaml
@@ -17,6 +17,11 @@ inputs:
     required: false
     type: string
     default: "dev"
+
+  package:
+    required: false
+    type: string
+    default: ""
   
 runs:
   using: "composite"
@@ -63,3 +68,22 @@ runs:
           echo -e "\033[31m Release tag ${{ github.ref_name }} is not on production branch. Aborting release build!"
           exit 1
         fi'
+
+    - name: 'Update package version'
+      if: ${{ env.REF_NAME == 'production' && github.event_name == 'release' && inputs.package == 'npm' }}
+      uses: actions/setup-node@v3
+      # Update the version in package.json
+      run: |
+        current_version=$(node -p "require('./package.json').version")
+        node -e "const fs = require('fs'); const packageJson = JSON.parse(fs.readFileSync('./package.json')); packageJson.version = '${{ github.ref_name }}'; fs.writeFileSync('./package.json', JSON.stringify(packageJson, null, 2));"
+        updated_version=$(node -p "require('./package.json').version")
+        if [ "$current_version" == "$updated_version" ]; then
+          echo -e "\033[31m Failed to update package version to ${{ github.ref_name }}. Aborting release build!"
+          exit 1
+        fi
+        npm version ${{ github.ref_name }}
+        git config --global user.email "github@21.com"
+        git config --global user.name "GitHub"
+        git add package.json
+        git commit -m "Update package version to ${{ github.ref_name }}"
+        git push origin ${{ github.ref_name }}
